name: UIA Bench

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci || npm i

      - name: Run full A1–A9 suite
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          set -euo pipefail
          mkdir -p results
          ts=$(date -u +"%Y-%m-%dT%H%M%SZ")

          echo ">>> START UIA batch"
          ( node index.js --A=all --prompts=6 --concurrency=4 --log="results/uia_run_${ts}.jsonl" 2>&1 | tee "results/console_${ts}.log" ) || true
          echo ">>> END UIA batch"

          if [ -s "results/uia_run_${ts}.jsonl" ]; then
            echo "✅ UIA complete"
            cp "results/uia_run_${ts}.jsonl" results/latest.jsonl
          elif [ -s "uia_log.jsonl" ]; then
            cp "uia_log.jsonl" "results/uia_run_${ts}.jsonl"
            cp "results/uia_run_${ts}.jsonl" results/latest.jsonl
          else
            echo "⚠️ No UIA output"
            : > results/latest.jsonl
          fi

          echo ">>> START baseline"
          ( node baseline.js --model=gpt-4o-mini --log="results/baseline_${ts}.jsonl" --t=0.7 2>&1 | tee "results/baseline_console_${ts}.log" ) || true
          echo ">>> END baseline"

          if [ -s "results/baseline_${ts}.jsonl" ]; then
            echo "✅ Baseline complete"
            cp "results/baseline_${ts}.jsonl" results/baseline_latest.jsonl
          else
            echo "⚠️ No baseline output"
          fi

          echo "UIA Bench completed at $(date -u)" > results/readme.txt
          echo ">>> File sizes"
          wc -c results/*.jsonl 2>/dev/null || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: uia-bench-${{ github.run_id }}
          path: results/**
          if-no-files-found: warn

      - name: Commit results
        if: always()
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add results/ || true
          git commit -m "bench: update results (run ${{ github.run_id }})" || echo "no changes"
          git push || true