name: UIA Bench

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"  # runs daily at 05:00 UTC (optional)

permissions:
  contents: write  # allow commit step below

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci || npm i

      - name: Run full A1–A9 suite
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          set -euo pipefail
          mkdir -p results
          ts=$(date -u +"%Y-%m-%dT%H%M%SZ")

          echo ">>> START batch call"
          ( node index.js --A=all --prompts=6 --log="results/uia_run_${ts}.jsonl" 2>&1 | tee "results/console_${ts}.log" ) || true
          echo ">>> END batch call"

          echo ">>> List results/"
          ls -la results || true

          # Primary target (new code path)
          if [ -s "results/uia_run_${ts}.jsonl" ]; then
            echo "✅ Found results/uia_run_${ts}.jsonl"
            cp "results/uia_run_${ts}.jsonl" results/latest.jsonl
          # Fallback to legacy path (old index.js writes here)
          elif [ -s "uia_log.jsonl" ]; then
            echo "✅ Found legacy ./uia_log.jsonl (copying)"
            cp "uia_log.jsonl" "results/uia_run_${ts}.jsonl"
            cp "results/uia_run_${ts}.jsonl" results/latest.jsonl
          else
            echo "⚠️ No JSONL found; leaving an empty placeholder."
            : > results/latest.jsonl
          fi

          # Tiny proof so Artifacts always exist
          echo "UIA Bench completed at $(date -u)" > results/readme.txt

          # Show sizes for debugging
          echo ">>> File sizes"
          wc -c results/*.jsonl 2>/dev/null || true
          exit 0

      - name: Upload artifacts (logs + results)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: uia-bench-${{ github.run_id }}
          path: results/**
          if-no-files-found: warn

      - name: Commit results to repo (optional)
        if: always()
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add results/ || true
          git commit -m "bench: update results (run ${{ github.run_id }})" || echo "no changes"
          git push || true