name: UIA Bench (Liquid AI)

on:
  workflow_dispatch:
    inputs:
      model:
        description: "Liquid model ID (e.g., leap, apollo, lfm-40b)"
        required: false
        default: "leap"
      scope:
        description: "A-scope (all, A1, A1-A3, A1,A2,A3)"
        required: false
        default: "all"
      concurrency:
        description: "Parallel requests"
        required: false
        default: "6"
      max_tokens:
        description: "Max completion tokens"
        required: false
        default: "120"
      temperature:
        description: "Sampling temperature"
        required: false
        default: "0.2"
  schedule:
    - cron: "0 7 * * *"  # 07:00 UTC

permissions:
  contents: write

concurrency:
  group: uia-bench-liquid-${{ github.ref }}
  cancel-in-progress: false

jobs:
  baseline-liquid:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      NODE_OPTIONS: "--max-old-space-size=2048"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: "npm" }
      - run: npm ci || npm i

      - name: Run Liquid AI baseline
        env:
          LIQUID_API_KEY: ${{ secrets.LIQUID_API_KEY }}
          MODEL_ID: ${{ github.event.inputs.model || 'leap' }}
          SCOPE: ${{ github.event.inputs.scope || 'all' }}
          MAX_TOKENS: ${{ github.event.inputs.max_tokens || '120' }}
          TEMPERATURE: ${{ github.event.inputs.temperature || '0.2' }}
          CONCURRENCY: ${{ github.event.inputs.concurrency || '6' }}
        run: |
          set -euo pipefail
          mkdir -p results
          TS=$(date -u +"%Y-%m-%dT%H%M%SZ")
          echo "TS=$TS" >> $GITHUB_ENV
          echo "::notice title=Liquid AI Baseline::Starting baseline ${TS} (model=$MODEL_ID, scope=$SCOPE)"
          node baseline_liquid.js \
            --model="$MODEL_ID" \
            --A="$SCOPE" \
            --concurrency="$CONCURRENCY" \
            --max_tokens="$MAX_TOKENS" \
            --temperature="$TEMPERATURE" \
            --log="results/baseline_liquid_${TS}.jsonl" \
          2>&1 | tee "results/baseline_liquid_console_${TS}.log"
          echo "::notice title=Liquid AI Baseline::Completed"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: baseline-liquid-results
          path: |
            results/baseline_liquid_*.jsonl
            results/baseline_liquid_console_*.log
          retention-days: 14

  uia-liquid:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      NODE_OPTIONS: "--max-old-space-size=2048"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: "npm" }
      - run: npm ci || npm i

      - name: Run Liquid AI UIA
        env:
          LIQUID_API_KEY: ${{ secrets.LIQUID_API_KEY }}
          MODEL_ID: ${{ github.event.inputs.model || 'leap' }}
          SCOPE: ${{ github.event.inputs.scope || 'all' }}
          MAX_TOKENS: ${{ github.event.inputs.max_tokens || '120' }}
          TEMPERATURE: ${{ github.event.inputs.temperature || '0.2' }}
          CONCURRENCY: ${{ github.event.inputs.concurrency || '6' }}
        run: |
          set -euo pipefail
          mkdir -p results
          TS=${TS:-$(date -u +"%Y-%m-%dT%H%M%SZ")}
          echo "::notice title=Liquid AI UIA::Starting UIA ${TS} (model=$MODEL_ID, scope=$SCOPE)"
          node index_liquid.js \
            --model="$MODEL_ID" \
            --A="$SCOPE" \
            --prompts=6 \
            --concurrency="$CONCURRENCY" \
            --max_tokens="$MAX_TOKENS" \
            --temperature="$TEMPERATURE" \
            --log="results/uia_liquid_${TS}.jsonl" \
          2>&1 | tee "results/uia_liquid_console_${TS}.log"
          echo "::notice title=Liquid AI UIA::Completed"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: uia-liquid-results
          path: |
            results/uia_liquid_*.jsonl
            results/uia_liquid_console_*.log
          retention-days: 14

  compare:
    if: always()
    needs: [baseline-liquid, uia-liquid]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: "npm" }
      - run: npm ci || npm i

      - uses: actions/download-artifact@v4
        with: { name: baseline-liquid-results, path: results }
      - uses: actions/download-artifact@v4
        with: { name: uia-liquid-results, path: results }

      - name: Summarize Liquid AI results
        run: |
          set -euo pipefail
          echo "::group::Generating summary"
          if [ -f summarize_all.js ]; then
            node summarize_all.js results/baseline_liquid*.jsonl results/uia_liquid*.jsonl
          else
            # minimal inline summary if script is absent
            node -e '
              const fs=require("fs");
              const glob=require("fs").readdirSync("results").filter(f=>/baseline_liquid_.*\.jsonl$/.test(f));
              const base=glob[0] && fs.readFileSync("results/"+glob[0],"utf8").trim().split("\n").map(JSON.parse).filter(r=>r.event==="BASELINE:row");
              const lat=base?base.map(r=>+r.latencyMs||0).sort((a,b)=>a-b):[];
              const q=p=>lat.length?lat[Math.floor((p/100)*(lat.length-1))]:null;
              const avg=lat.length?Math.round(lat.reduce((a,b)=>a+b,0)/lat.length):null;
              const lines=[];
              lines.push("# Liquid AI Brief");
              lines.push("");
              lines.push(`Baseline rows: ${base?base.length:0}`);
              lines.push(`Latency avg ${avg}ms (p50 ${q(50)} / p90 ${q(90)} / p99 ${q(99)})`);
              fs.writeFileSync("results/summary_all.md", lines.join("\n"));
              fs.writeFileSync("results/summary_all.csv", "metric,value\navg_latency_ms,"+(avg||"")+"\n");
            '
          fi
          echo "::endgroup::"
          echo "::group::Liquid AI Brief"
          cat results/summary_all.md || true
          echo "::endgroup::"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: liquid-summary
          path: |
            results/summary_all.csv
            results/summary_all.md
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: all-liquid-results
          path: results/
          retention-days: 14
