name: UIA Bench

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"  # runs daily at 05:00 UTC (optional)

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci || npm i

      - name: Run full A1–A9 suite
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          set -euo pipefail
          mkdir -p results
          ts=$(date -u +"%Y-%m-%dT%H%M%SZ")

          # Run and always capture console output (don’t fail the step if Node exits non-zero)
          ( node index.js --A=all --prompts=6 --log=uia_log.jsonl 2>&1 | tee "results/console_${ts}.log" ) || true

          # Try to locate the log wherever your script wrote it
          LOG_CANDIDATE="$(find . -maxdepth 3 -type f -name 'uia_log.jsonl' | head -n 1 || true)"

          if [ -n "${LOG_CANDIDATE}" ] && [ -f "${LOG_CANDIDATE}" ]; then
            echo "✅ Found log at: ${LOG_CANDIDATE}"
            cp "${LOG_CANDIDATE}" "results/uia_run_${ts}.jsonl"
            cp "results/uia_run_${ts}.jsonl" results/latest.jsonl
          else
            echo "⚠️ uia_log.jsonl not found. Saving empty JSONL so artifacts still exist."
            echo "" > results/latest.jsonl
          fi

          # Optional summary
          if [ -f view_spark.js ]; then
            node view_spark.js results/latest.jsonl > "results/summary_${ts}.md" || true
            cp "results/summary_${ts}.md" results/latest.md || true
          fi

          # Never fail this step due to missing files past this point
          exit 0
